image: gitpod/workspace-dotnet
ports:
  - port: 8080
    onOpen: open-preview
tasks:
  - init: dotnet new web -o gitpod_asp
    command: >
      cd gitpod_asp/ &&
      dotnet run --urls http://0.0.0.0:8080
