image: gitpod/workspace-dotnet
tasks:
  - init: wget https://github.com/OmniSharp/omnisharp-vscode/releases/download/v1.25.0/csharp-1.25.0-linux-x64.vsix && code --install-extension csharp-1.25.0-linux-x64.vsix && rm csharp-1.25.0-linux-x64.vsix
  - command: dotnet run -p ToDoAPI --urls http://*:5215
ports:
  - port: 5215
    onOpen: open-preview
