image: gitpod/workspace-dotnet
ports:
  - port: 8080
    onOpen: open-preview
tasks:
  - init: dotnet new web -o GitpodASP
    command: >
      cd GitpodASP/ &&
      dotnet run --urls http://0.0.0.0:8080
